# Generated by Django 2.1.1 on 2018-09-08 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('category_description', models.CharField(max_length=200)),
                ('category_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tb_Category',
            },
        ),
        migrations.CreateModel(
            name='Dealers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealer_name', models.CharField(max_length=100)),
                ('dealer_address', models.CharField(max_length=250)),
                ('dealer_phnr', models.IntegerField()),
                ('dealer_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tb_Dealer',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_description', models.CharField(max_length=200)),
                ('product_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tb_Product',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=100)),
                ('shop_address', models.CharField(max_length=250)),
                ('shop_active', models.BooleanField(default=True)),
                ('dealers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.Dealers')),
            ],
            options={
                'db_table': 'tb_Shop',
            },
        ),
        migrations.CreateModel(
            name='Product_Attributes',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='assignment.Product')),
                ('attribute_value', models.CharField(max_length=100)),
                ('attribute', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assignment.Attributes')),
            ],
            options={
                'db_table': 'tb_Product_Attributes',
            },
        ),
        migrations.AddField(
            model_name='dealers',
            name='product',
            field=models.ManyToManyField(to='assignment.Product'),
        ),
        migrations.AddField(
            model_name='category',
            name='product',
            field=models.ManyToManyField(to='assignment.Product'),
        ),
    ]
