# Generated by Django 2.1.1 on 2018-09-09 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0003_auto_20180908_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products_Attributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_value', models.CharField(max_length=100)),
                ('attribute', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assignment.Attributes')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assignment.Product')),
            ],
            options={
                'db_table': 'tb_Products_Attributes',
            },
        ),
    ]
