# Generated by Django 2.1.1 on 2018-09-09 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0004_products_attributes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_attributes',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='product_attributes',
            name='product',
        ),
        migrations.DeleteModel(
            name='Product_Attributes',
        ),
    ]
